version: "3.9"

services:
  postgres:
    image: postgres:16-alpine
    container_name: tasker-db
    restart: unless-stopped
    environment:
      POSTGRES_USER: tasker
      POSTGRES_PASSWORD: taskerpass
      POSTGRES_DB: tasker
      TZ: Asia/Kolkata
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U tasker -d tasker" ]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7-alpine
    container_name: tasker-redis
    restart: unless-stopped
    command: [ "redis-server", "--appendonly", "yes" ]
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 10s
      timeout: 3s
      retries: 5

  adminer:
    image: adminer:latest
    container_name: adminer_container
    restart: always
    ports:
      - "8080:8080" # Access Adminer in your browser at http://localhost:8080
    environment:
      ADMINER_DEFAULT_SERVER: postgres # This connects Adminer to the 'postgres' service defined above
    depends_on:
      - postgres # Ensure the database starts before Adminer

volumes:
  postgres_data:
  redis_data:
